version: '3'
services:
  consul-base:
    image: consul:latest
    container_name: "consul-base"
    ports:
      - '8300:8300'
      - '8301:8301'
      - '8301:8301/udp'
      - '8500:8500'
      - '8600:8600'
      - '8600:8600/udp'
    command: "agent -dev -bind 0.0.0.0 -client 0.0.0.0 -data-dir=/consul-data"
    volumes:
      - ./consul-data:/consul-data
  consul-agent:
    image: consul:latest
    command: "agent -bind 0.0.0.0 -client 0.0.0.0 -join consul-base"
    depends_on:
      - consul-base
  vault:
    image: "vault"
    depends_on:
      - consul-base
      - consul-agent
    links:
      - "consul-base:consul"
    environment:
      - VAULT_ADDR=http://vault:8200
    ports:
      - "8200:8200"
    volumes:
      - ./config:/config
    command: "vault server -config=/config/vault.hcl -log-level=trace"